var classText = {

	"class121":[
		"Prof. was enthusiastic",
		"I liked the actual intrest he had for Math & his little quirks. Made it interesting & fun to go to class. 10/10 What a good guy.",
		"Your puzzles in your office are cool",
		"Entertaining and unique prof, made class fun. Like question breaks!",
		"Fun guy",
		"This course was perfect",
		"Prof was dope & funny. It's tough to make math fun but he did a fantastic job and always put in effort.",
		"His humor and passion to teach",
		"Easy going and understandable",
		"The professor explained things very clearly.",
		"I liked how enthusiastic the prof is about the subject and how he decided to present the material on wednesday all as clicker questions",
		"The material was relatively interesting and the prof was always enthusiastic and ready to teach.",
		//"Your t-shirts",
		"It was my most entertaing by, Keep up the good work!",
		"Creative",
		"Well organized and manageable workload. AMAZING prof.",
		"The prof! makes math interesting",
		"I enjoyed the organization and the passion for math that was being spread.",
		"The profs halloween costume, and math I guess.",
		"The notes and drawing out pic from applied problems",
		"The professor. He make me so happy. I like his jokes and pre-class jokes.",
		"The explaination of the material from the instructor.",
		"Prof with high quality memes",
		"I don't like calc but I like Daniel (the prof)",
		"The prof was great & the online videos were much better than having to sit through a 3 hour lecture. Keep the prof",
		"Fun course and interesting lessons",
		"Keep professor Dan.",
		"The professor is both personable and good at teaching. Seems easy to approach.",
		"I liked the questions we went through during class-time. It helped my understanding on the subject.",
		"The prof was interactive and wanted to ensure everyone understood before continuing. He also make the classes interesting.",
		"I'll Miss You DANNY! <3",
		"Easy to understand. Thouroghly goes through content and questions.",
		"The prof, made calculus more intersting.",
		"Everything is good",
		"I thoroughly enjoyed the ''flipped'' style teaching, it gave a better understanding for difficult problems. Danny is a fantastic teacher, give him a raise.",
		"Professor was always there for clarifications. Content was clear. Help was provided.",// Like the layout.",
		"We focused on what students needed help with (example wise)",
		"Nothing to suggest, it's perfect!",
		"Reviewing practice problems we struggled with. Short question breaks in class! Awesome prof.",
		"Very engaging",
		"Well organized and clear to me.",
		"Have a good day Prof if you are reading this.",
		//"The organization of it. The jokes",
		"I liked the structure of this course, and how the lessons after the videos were taylored to the students comments, as well as after the homework was done. The proffesor kept things interactive and interesting, and was very willing to help students in office hours. Overall I have come out of this course no longer dispising math. Thank you!",
		"I absolutely loved everything. The set up (lectures out of class, going over questions in class), took a little while to get used to, but it encouraged me to take more time to learn content and seek out answers. This and the professor's enthusiasm made this a memorable course that definitely inspires me to take more math-related subjects",
		"The professor makes each class fun, rather than just being monotone for the whole semester.",
		"GG well played.",
		"Danny teaches well.",
		"The Prof. He was very energetic and fun. Had multiple techniques to keep the class interested. Props to Daniel!",
		"Love the prof! He is an effective and fun teacher - the material was presented clearly.",
		"The funny sentences at the begining of lecture. The prof was very funny and knew his stuff.",
		"The fact that the prof jumped in like a ninja for halloween. Also class was very well presented and clear. Easy to follow and genuinly enjoyable to go to class. We should have a snowball fight.",
		//"Very well organized, run the best out of all the classes I'm taking this year.",
		"Class was always enjoyable. Material was presented in an effective manner. Thanks for a great semester of enjoyable content and stories. No suggestions you taught the course flawlessly.",
		//"I liked learning new things about math and learning of the strange edge cases",
		//"It's well-organized. Q&A Break.",
		"The instructor made the course actually interesting, usually I sleep during the math classes.",
		"We need more Danny in the winter semester.",
		"In general I don't like math but, Daniel made it fun and easy to pay attention most of the times. It was kind of difficult of a course.",
		//"Very nice",
		"You were a very fun teacher, made coming to class interesting.",
		//"Handsom Teacher",
		
	],

	"class124":[
		"RORABAUGH!! The Best man, you seriously the coolest. Keep doing you.",
		"I liked the professor as he made the lectures interesting and funny. I also liked the organization of the course, everythign was easy to [illegible word].",
		"I like math.",
		"Even though there were many things learned in high school, Professor Rorabaugh taught us better and more effective strategies.",
		"Nice that teacher was available right after class for immediate questions.",
		"The instructor was nice.",
		"Sometimes there are funny jokes.",
		"The prof is awesome - very engaging and entertaining. Highly recommend.",
		"The puns and jokes my dude Rorabaugh made. Really kept the class live.",
		"The class time. Working with the Prof is a lot more helpful than the videos.",
		"I like coming to class and working through questions together. It's helpful to see the process.",
		"Dr. Rorabaugh made class fun and engaging. THANK YOU!",
		"Overall, the material was presented in an enthusiastic way and the professors really did know what they were teaching, so it was king of interesting.",
		"The teacher was extremely helpful.",
		"The proff (Dr. Dan) is amazing and easy to approach with concerns about the course.",
		"The material was presented in an engaging & interesting manner.",
		"The professor is very humourous and easy to understand",
		//"Danny Rorabaugh. MOST FUN I'VE HAD WITH CLOTHES ON....",
	],

	"class124b":[
		"I liked the material we learned.",
		//"good humour.",
		"The content was very interesting",
		"Danny was the best",
		"Prof was funny as [****], made class better. Liked the access to math vids.",
		"The instructor was nice and personable.",
		"Danny is a fantastic teacher. Keep him teaching forever, he's so good.",
		"The professor was genuinely interested in the material and the teaching of said material.",
		"Professors were great to learn from, interesting to listen to, and helpful!",
		"Rorabaugh is very friendly & easily approachable",
		"The matierial was available online. Danny was always helpful and available.",
		"The professor was very cool",
		"Made class engaging",
		"Math!",
		"great profs",
		"Great Course!!",
		"Enjoyed the questions that got answered during the class",
		"Prof. was good, solid teaching abilities",
		"Great professor",
		"Don't change the prof.",
		"The professor is humorous and funny ^.^",
		//"1. Funny  2. Math is good! when you play more",
	],
	
	"class235":[
		"[picture of a cow wearing a propeller hat]",
		"The instructor explains the course material clearly and smoothly, and also the course is overall well-organized.",
		"Danny is a G.",
		"I just enjoy differential eqns!",
		"Applications the diff can be used in an Engineering setting.",
		"Dr. Danny is incredibly smart and a fantastic teacher. Only class I actually go to, for a good reason.",
		"Good workload, intuitive material and ample resources available. Seems the most \"relevant\" so far.",
		"Notes are well annotates.",
		"Enthusiastic instructor w/ great notes.",
		"Printout slides to make notes.",
		"Prof was very good.",
		"Application to the real world.",
		"Danny you do you, great job! We love you <3",
		"The enthusiasm by the professor teaching this course.",
		"I like the way the material was presented. By-weekly quizzes made it easy to keep up with the material. Keep teaching this course :)",
		"Dr. Danny is the best prof. Teaches really well and is exciting, funny and great to listen to. Makes it easy to listen to the lecture. Dr. Danny is 11/10. Have Dr. Danny keep teaching this course.",
		"Everything. Great prof & interesting course. Really enjoyed this course.",
		"Dr. Danny is great!",
		"The quizzes were a blast. Effective way of forcing students to learn material.",
		"The instructor was great - very effective teacher. Material was set at a reasonable pace. Not too stressful.",
		"The quizzes were fait and I love math.",
		"Prof is unreal.",
		"The Prof.",
		"Well organized. Homework questions were awesome, really helped me learn the material and were very applicable to quizzes.",
		"Great teacher, communicates well.",
		"Excellent professor. Very engaging and obviously passionate about the material.",
		"You are a very effective teacher and I really like your enthusiasm for the course material as well as your proficiency in English. And it was very applicable to other courses.",
		"You rock Dr. Danny! Seriously, this is our best course in terms of clarity and interestingness (if that's a word).",
		"The awesome teacher, and the amazing power of math.",
		"Both Dr. Rorabaugh and his teaching / delivery method. He is very knowledgeable and conducted lectures very effectively.",
		"Well taught, great instructor.",
		"Great prof, made material easy to learn.",
		"It was really well taught. I felt coming to class made learning beneficial. The teacher is really good. The tests were fair as was the marking. I felt learning this helps in my other courses.",
		"Dr. Dan was awesome. Good pace.",
		"Dr. Dan is \"The Man\" as we folk like to say! No complaints here. Quiz system is good. It's fine, people who complain about it probably didn't do the homework or go to class enough.",
		"Doc. Dan is an awesome dude. Fave prof qithout a doubt. Supe clear presentations and the Quizzes are fair. If you are not doing well in this course it's your own fault. Dan is the man.",
		"I liked the workload, organization, + biweekly quizzes. The schedule of the course encouraged active learning throughout the semester. The 6 quizzes (and marking only 5 toward the final grade) fosters good academic performace from students.",
		"It's structured very well. The homework + answers are a great learning resource. The biweekly quizzes are fair and forced me to study.",
		"I liked the use of the laptop and annotated notes. Made it easy to go back and check lecture notes in case you missed them in class or didn't quite understand the first time. 6 quizzes is a good number. I also like that it's best 5 out of 6 quizzes.",
		"My favourite Prof. this year by far! Thank you :)",
		"THe practice questions given to us before quizzes.",
		"I like that you post your own annotated notes in case we've missed writing something down. Also, thank you for teaching me my circuits course. This class is the only reason I'm doing ok in that class.",
		"Well organized and well taught. The prof is available for questions and is very helpful. He enjoys what he is teaching which makes the course and material more interesting and fun for the students.",
		"You are really clear and easy to listen to! I like that you go through and show all the steps to problems and you always respond well to questions. This is one of my favourite classes this term.",
		"I especially liked Dr. Rorabaugh's teaching of this course. Dr. Rorabaugh has been the best instructor I have had at Queen's! He was very clear in the presentation of the course material. He was also very approachable and helpful after class and was constantly trying to offer more help when needed.",
		"The Professor's enthusiasm and thoroughness with his explanations.",
		"I find this course very useful and intersting as well. My professor explains in an easy way, which is awesome. This course is excellent overall.",
		"Danny was great. Overall great job Danny.",
		"Super well organized, explanations are easy to understand & straight forward. :)",
		"Lots of practice problems; frequent, short quizzes.",
		"The bi-weekly quizzes allowed me to stay on top of the topics in the course; the instructor was intersting and funny to listen to.",
		"Good lecturer, good notes overall.",
		"The assessment content is fair and I feel the course reflects the tested material well. I also like the available practice problems and clear posted solutions. Course is good as is.",
		"Really good Prof. Very clear and easy to understand.",
		"Multicoloured slides; bi-weekly quizzes.",
		"This is the first decent prof for this course in 4 years or more. He can actually teach and isn't a pompus ass.",
		"Very good teaching style, fair assessments, practice problems were provided. Notes were available online.",
		"Great online notes; interesting classes; great speaker; bi-weekly quizzes.",
		"The professor was fantastic at presenting material and was available outside of class for help. Made me enjoy diffs. Hire the same prof again. He is 11/10, 12/10 with rice.",
		"DR. DANNY IS GREAT! The assessments are super fair and help a lot with keeping up with course content. Hire DR. DANNY again!!",
		"Really organized compared to my other courses. Really effective prof and material.",
		"How it's ECE specific and the applications are tailored to our program.",
		"Well organized, the format of doing many examples in a relatively small lecture hall is great. Dr. Rorabaugh is an amazing teaching. Keep doing you Doc! Keep Dr. Dan teaching this and it's impossible to improve it.",
		"Got marks back quickly.",
		//text_121[66] = "DANNY MY BOY! He's Ferda",
	],
	
	"class111":[
		"Great at making sure we understand processes w/o overusage of calculator. Overall great teacher.",
		"His enthusiasm is beneficial & the way he explains things works well.",
		"The teacher gave many opportunities to practice material and improve grade.",
	],
	
	"class115":[
		"He is very willing to help us in any way he can: Knows the material very well and is a good instructor.",
		"Danny was a tough yet fair teacher. His tests were very difficult, but he offered many opportunities to improve our grades.",
		"The instructor understood the material very well and was able to teach it.",
		"Graded in timely manner.",
		"Knows matrerial well and grades fairly.",
		"Very good at one to one tutoring.",
		"Our instructor knows the subject very well. He teaches in a way that allows students to take a good amount of notes to study from.",
		"Mr. Rorabaugh has been very helpful to me in this course. His availability and encouragement of visiting him during office hours was very beneficial to my learning experience.",
		"Was entertaining and interesting. Kept class involved in lectures.",
		"He is a good teacher and motivated about the subject he teaches, I think he should at least add practice exams to the course.",
		"Everything was fine. He really knows what he is talking about.",
		"Very knowledgeable, lots of office hours, easy to understand him.",
		"The professor clearly has an in depth understanding of the material.",
		"I think he grades kind of hard, but I think he is a good teacher.",
		"He knew what he was talking about & cared for students.",
		"I'm not sure what about this teaching style was so good, but it really helped me remember material. I think it was the many examples we did in class.",
		"He is extremely passionate about mathematics which helped me to be just as excited.",
		"He is enthusiastic & works one-on-one with you.",
		"Knows information and communicates it well.",
		"Makes course more involving.",
		"I think he is a good teacher; however, his tests are difficult.",
		"I actually love the way my professor taught his class. I think that he thoroughly taught all of the material for each chapter. Sometimes I feel that he taught too much information, but in a sense that is just me being lazy. Professor Rorabaugh is one of the best teachers I have ever had. Great work.",
	],
	
	"class122":[
		"This is Danny's class. // Calculus is what we do. // It is a great class.",
		"Algebra is fun // but that's just level one. // Next comes calculus // it makes you like math way less // until you discover // how it can relate one thing to another. // Now I feel quick & smart // It's now time to part.",
		"He was always available to help students when need be.",
		"Graded efficiently.",
		"Good attitude.",
		"He's just a little out there but good teacher.",
		"Mr. Rorabaugh has done a fantastic job presenting the material.",
		"Knowledgeable, good at conveying knowledge.",
		"Good course, learned a lot.",
		"Went at right level each class.",
		"Fair grader, gave students many chances to improve their grades.",
		"He is funny and easy to listen to.",
	],
	
	"class142":[
		"Danny saved my career. He has a knack for explaining things how I can learn it.",
		"He is great. Danny should teach this instead of professors.",
		"Very open for discussion.",
		"Always there to help - makes class fun.",
		//"This is a ridiculous pre-req for marine science majors.",
	],
	
	"class170":[
		"Grades quickly, gives a lot of examples.",
		"He explained the material very well & always wanted us to know the material inside & out. Frequent quizzes but they helped make sure we understood what we were learning.",
		" 'Q' was great; he had great agents.",
		"Great course.",
		"Is patient and calm with students.",
		"He is very passionate and helpful! Outside of class he is available to help with homework. Communication skills when giving notes could be improved.",
		"Understands the course subject & answers questions & wants to help students understand.",
		"The instructor is clear. He tries to make things relatable. He grades fairly. He does want people to do well. Study sessions and practice exams helped.",
		"Teacher explains well, tries to help.",
		"Explains material well. Tough grader.",
		"Teacher covered everything we saw on the test, there were no surprises and was no unfamiliar formatting of Q[uestions]s.",
		"Good examples and descriptions of terms.",
		"I think he was a good teacher, but answers to the practice exams would have been helpful while studying for the midterms.",
		"Very helpful and made himself available to students when extra time was needed.",
	],
	
	"class401":[
		"I thought the assignments were just the right level, at times challenging but doable with what we learned. The courseload was not too high, but I think I learned quite a lot.",
		"I enjoyed the fun puzzles the prof posted online.",
		"The prof was a great teacher and the material of this course is interesting and actually applicable.",
		"This course had cool material. Danny is a legend. Great prof. Give this guy tenure!",
		"This course was exceptional. Danny is a very engaging professor and went out of his way to ensure the course was as engaging as he was. Whether it be challenge questions at the start of class, lectures spend on combinatorial games, perusing the online mathematics community, or watching related videos on Numberphile, I was never bored in this course. This is one of the best courses I have had during my undergrad, and I hope I am able to have Danny as a professor again. Well done!",
		"I really liked how the grades were distributed and the biweekly homework assignments.",
		"Amazing prof!! Lectures very engaging! I found the inclass exercises & review exercises very helpful!",
		"I like how the prof did a review question at the beginning of each class so we could practice the concepts and make sure we understand them. I also liked how we got to play games sometimes or do other fun activities to relate what we learned in class to real life.",
		"Material was presented clearly and effectively, and the examples given are always appreciated. Review exercises done in class are a great way to enhance understanding.",
		"I really like how this course often made use of in class activities and exercises. They were very good at keeping one attentive for an early morning class.",
		"Classes were fun. Lots of review exercises.",
		"Prof. Rorabaugh was a great professor. You could tell he had a great passion and enthusiasm for the course and enjoyed teaching us. This made it my favourite course this semester. Material was presented clearly.",
		"This is quite different content compared to my other math courses, which I enjoyed. Helped me view some areas of math in a different way.",
		"Interesting content. Best overall math instructor I have been taught by ever I think! Assignments were good and fair!",
		"Professor Rorabaugh has a lot of energy and enthusiasm.",
		"The content was presented clearly with many examples. The prof was super approachable and really cares about his students. Real life examples! :) Easy to follow.",
		"Intersting assignment problems. Interesting extensions on material in class (OEIS, Bacon, open problems, etc).",
	],
	
};
