var bodyText = "", currentHex, score = 0, hexInfo, bigDim, dim, inverse;

function submitCor() {
	var C0r = document.getElementById("cor").value;
	var cr = C0r.toLowerCase().replace(/[^a-z]+/g, "");
	currentHex = corDict[cr];
	if (currentHex === undefined) {
		window.alert(cr + " is not a standard HTML color name.");
	} else {
		hexInfo = hexDict[currentHex];
		if (hexInfo[0]===0) {
			hexDict[currentHex][0] = 1;
			score++;
			document.getElementById("score").innerHTML = score;
			bigDim = Math.max(Math.min(window.innerWidth - 10, window.innerHeight - 85), 50); 
			document.getElementById("body").style.width = bigDim + "px";
			dim = Math.floor((bigDim - 5) / Math.ceil(Math.sqrt(score)));
			document.getElementById("corBoxSpecs").innerHTML = ".corBox{display:inline-box;float:left;border-radius:5%;width:" + dim + "px;height:" + dim + "px;}";
			inverse = invertColor(currentHex);
			bodyText += "<div id="+currentHex+" class=\"corBox\" style=\"background-color:"+currentHex+";text-align:center;color:"+inverse+";\"><h5>"+currentHex.toLowerCase()+"</h5><h6>"+hexInfo[1]+"</h6></div>";
			document.getElementById("body").innerHTML = bodyText;
		} else {
			window.alert("You already have "+hexInfo[1]+".");
		};
	};
	document.getElementById("cor").value = "";
}

function invertColor(hexTripletColor) {
        var color = hexTripletColor;
        color = parseInt(color.substring(1),16); // remove # & convert to integer
        color = 0xFFFFFF - color; // invert
        color = color.toString(16); // convert to hex string
        color = "#" + (("000000" + color).slice(-6)); // pad with leading zeros
        return color;
}

// http://www.w3schools.com/colors/colors_names.asp
var corDict = {
aliceblue:"#F0F8FF",
alice:"#F0F8FF",
antiquewhite:"#FAEBD7",
antique:"#FAEBD7",
aqua:"#00FFFF",
aquamarine:"#7FFFD4",
marine:"#7FFFD4",
mediumaquamarine:"#66CDAA",
mediumaqua:"#66CDAA",
mediummarine:"#66CDAA",
azure:"#F0FFFF",
beige:"#F5F5DC",
bisque:"#FFE4C4",
black:"#000000",
blanchedalmond:"#FFEBCD",
almond:"#FFEBCD",
blanched:"#FFEBCD",
blue:"#0000FF",
darkblue:"#00008B",
lightblue:"#ADD8E6",
mediumblue:"#0000CD",
violetblue:"#8A2BE2",
brown:"#A52A2A",
burlywood:"#DEB887",
burly:"#DEB887",
wood:"#DEB887",
cadetblue:"#5F9EA0",
cadet:"#5F9EA0",
chartreuse:"#7FFF00",
chocolate:"#D2691E",
coral:"#FF7F50",
lightcoral:"#F08080",
cornflowerblue:"#6495ED",
flowerblue:"#6495ED",
cornflower:"#6495ED",
cornsilk:"#FFF8DC",
silk:"#FFF8DC",
crimson:"#DC143C",
cyan:"#00FFFF",
darkcyan:"#008B8B",
lightcyan:"#E0FFFF",
dodgerblue:"#1E90FF",
dodger:"#1E90FF",
firebrick:"#B22222",
fire:"#B22222",
brick:"#B22222",
floralwhite:"#FFFAF0",
floral:"#FFFAF0",
forestgreen:"#228B22",
forest:"#228B22",
fuchsia:"#FF00FF",
gainsboro:"#DCDCDC",
ghostwhite:"#F8F8FF",
ghost:"#F8F8FF",
gold:"#FFD700",
goldenrod:"#DAA520",
golden:"#DAA520",
darkgoldenrod:"#B8860B",
darkgolden:"#B8860B",
lightgoldenrodyellow:"#FAFAD2",
goldenrodyellow:"#FAFAD2",
goldenyellow:"#FAFAD2",
lightgoldenrod:"#FAFAD2",
lightgolden:"#FAFAD2",
palegoldenrod:"#EEE8AA",
palegolden:"#EEE8AA",
gray:"#808080",
grey:"#808080",
darkgray:"#A9A9A9",
darkgrey:"#A9A9A9",
dimgray:"#696969",
dimgrey:"#696969",
lightgray:"#D3D3D3",
lightgrey:"#D3D3D3",
green:"#008000",
darkgreen:"#006400",
lightgreen:"#90EE90",
palegreen:"#98FB98",
greenyellow:"#ADFF2F",
honeydew:"#F0FFF0",
honey:"#F0FFF0",
dew:"#F0FFF0",
indianred:"#CD5C5C",
indian:"#CD5C5C",
indigo:"#4B0082",
ivory:"#FFFFF0",
khaki:"#F0E68C",
darkkhaki:"#BDB76B",
lavender:"#E6E6FA",
lavenderblush:"#FFF0F5",
blush:"#FFF0F5",
lawngreen:"#7CFC00",
lawn:"#7CFC00",
lemonchiffon:"#FFFACD",
lemon:"#FFFACD",
chiffon:"#FFFACD",
lime:"#00FF00",
limegreen:"#32CD32",
linen:"#FAF0E6",
magenta:"#FF00FF",
darkmagenta:"#8B008B",
maroon:"#800000",
midnightblue:"#191970",
midnight:"#191970",
nightblue:"#191970",
night:"#191970",
mintcream:"#F5FFFA",
cream:"#F5FFFA",
mint:"#F5FFFA",
mistyrose:"#FFE4E1",
rose:"#FFE4E1",
misty:"#FFE4E1",
moccasin:"#FFE4B5",
navajowhite:"#FFDEAD",
navajo:"#FFDEAD",
navy:"#000080",
navyblue:"#000080",
oldlace:"#FDF5E6",
lace:"#FDF5E6",
old:"#FDF5E6",
olive:"#808000",
olivedrab:"#6B8E23",
drab:"#6B8E23",
darkolivegreen:"#556B2F",
darkolive:"#556B2F",
orange:"#FFA500",
darkorange:"#FF8C00",
redorange:"#FF4500",
orchid:"#DA70D6",
darkorchid:"#9932CC",
mediumorchid:"#BA55D3",
papayawhip:"#FFEFD5",
papaya:"#FFEFD5",
whip:"#FFEFD5",
peachpuff:"#FFDAB9",
peach:"#FFDAB9",
puff:"#FFDAB9",
peru:"#CD853F",
pink:"#FFC0CB",
deeppink:"#FF1493",
hotpink:"#FF69B4",
hot:"#FF69B4",
lightpink:"#FFB6C1",
plum:"#DDA0DD",
powderblue:"#B0E0E6",
powder:"#B0E0E6",
purple:"#800080",
mediumpurple:"#9370DB",
rebeccapurple:"#663399",
rebecca:"#663399",
red:"#FF0000",
darkred:"#8B0000",
orangered:"#FF4500",
violetred:"#C71585",
mediumvioletred:"#C71585",
palevioletred:"#DB7093",
rosybrown:"#BC8F8F",
rosy:"#BC8F8F",
royalblue:"#4169E1",
royal:"#4169E1",
saddlebrown:"#8B4513",
saddle:"#8B4513",
salmon:"#FA8072",
darksalmon:"#E9967A",
lightsalmon:"#FFA07A",
sandybrown:"#F4A460",
sandy:"#F4A460",
sand:"#F4A460",
seagreen:"#2E8B57",
sea:"#2E8B57",
darkseagreen:"#8FBC8F",
darksea:"#8FBC8F",
lightseagreen:"#20B2AA",
lightsea:"#20B2AA",
mediumseagreen:"#3CB371",
mediumsea:"#3CB371",
seashell:"#FFF5EE",
shell:"#FFF5EE",
sienna:"#A0522D",
silver:"#C0C0C0",
skyblue:"#87CEEB",
sky:"#87CEEB",
deepskyblue:"#00BFFF",
deepsky:"#00BFFF",
lightskyblue:"#87CEFA",
lightsky:"#87CEFA",
slateblue:"#6A5ACD",
darkslateblue:"#483D8B",
mediumslateblue:"#7B68EE",
mediumslate:"#7B68EE",
slategray:"#708090",
slategrey:"#708090",
darkslategray:"#2F4F4F",
darkslategrey:"#2F4F4F",
darkslate:"#2F4F4F",
lightslategray:"#778899",
lightslate:"#778899",
lightslategrey:"#778899",
slate:"#708090",
snow:"#FFFAFA",
springgreen:"#00FF7F",
spring:"#00FF7F",
mediumspringgreen:"#00FA9A",
mediumspring:"#00FA9A",
steelblue:"#4682B4",
steel:"#4682B4",
lightsteelblue:"#B0C4DE",
lightsteel:"#B0C4DE",
tan:"#D2B48C",
teal:"#008080",
thistle:"#D8BFD8",
tomato:"#FF6347",
turquoise:"#40E0D0",
darkturquoise:"#00CED1",
mediumturquoise:"#48D1CC",
paleturquoise:"#AFEEEE",
violet:"#EE82EE",
darkviolet:"#9400D3",
blueviolet:"#8A2BE2",
mediumredviolet:"#C71585",
redviolet:"#C71585",
paleredviolet:"#DB7093",
wheat:"#F5DEB3",
white:"#FFFFFF",
whitesmoke:"#F5F5F5",
smoke:"#F5F5F5",
yellow:"#FFFF00",
lightyellow:"#FFFFE0",
yellowgreen:"#9ACD32"
};

// http://www.w3schools.com/colors/colors_names.asp
var hexDict = {
"ja": [0,"Afrikaans, Danish, Dutch, Frisian, German"],
"po": [0,"Albanian"],
"āwo":[0,"Amharic"],
"nem fielaan":[0,"Arabic"],
"ayo":[0,"Armenian"],
"bəli": [0,"Azerbaijani"],
"bai":[0,"Basque"],
"dy":[0,"Belarusian"],
"hām̐":[0,"Bengali"],
"da":[0,"Bosnian, Bulgarian, Croatian"],
"si":[0,"Catalan, Galician"],
"oo":[0,"Cebuano, Filipino"],
"inde":[0,"Chichewa"],
"shì":[0,"Chinese"],
"iè":[0,"Corsican"],
"ano":[0,"Czech"],
"yes":[0,"English"],
"jes":[0,"Esperanto"],
"jah":[0,"Estonian"],
"kyllä":[0,"Finnish"],
"oui":[0,"French"],
"diakh":[0,"Georgian"],
"naí":[0,"Greek"],
"hā":[0,"Gujarati"],
"wi":[0,"Haitian Creole"],
"ba, babu": [0,"Hausa"],
"ae": [0,"Hawaiian"],
"haan": [0,"Hindi"],
"yog": [0,"Hmong"],
"igen":[0,"Hungarian"],
"já": [0,"Icelandic"],

"geen": [0,"Afrikaans"],
"jo": [0,"Albanian"],
"āyi":[0,"Amharic"],
"la":[0,"Arabic"],
"voch'":[0,"Armenian"],
"yox, xery": [0,"Azerbaijani"],
"ez":[0,"Basque"],
"niama, nie":[0,"Belarusian"],
"nā":[0,"Bengali"],
"ne":[0,"Bosnian, Bulgarian, Croatian, Czech, Esperanto"],
"no":[0,"Catalan, English, Corsican"],
"dili":[0,"Cebuano"],
"ayi":[0,"Chichewa"],
"méiyǒu, bù":[0,"Chinese"],
"innò":[0,"Corsican"],
"ingen, nej":[0,"Danish"],
"nee":[0,"Dutch, Frisian"],
"neniu":[0,"Esperanto"],
"ei":[0,"Estonian, Finnish"],
"hindi":[0,"Filipino"],
"non":[0,"French, Galician, Haitian Creole"],
"ar, ara":[0,"Georgian"],
"nein":[0,"German"],
"óchi":[0,"Greek"],
"nā":[0,"Gujarati"],
"pa gem (okenn)":[0,"Haitian Creole"],
"a": [0,"Hausa"],
"aole": [0,"Hawaiian"],
"nahin": [0,"Hindi"],
"tsis": [0,"Hmong"],
"nem":[0,"Hungarian"],
"nei": [0,"Icelandic"],

//https://translate.google.com/#en/ig/yes%0Ayes%2C%20please%0Ano%2C%20not%20me%0Ano%0Ano%2C%20thanks

"#9ACD32":[0,"Yellow&#173;Green"]
};