function draw_play_symbol(a,d,b,c){c.beginPath();c.moveTo(a,d-b/2);c.lineTo(a,d+b/2);c.lineTo(a+b,d);c.lineTo(a,d-b/2);c.closePath()}
function draw_reverse_symbol(a,d,b,c){c.beginPath();c.moveTo(a+b,d-b/2);c.lineTo(a+b,d+b/2);c.lineTo(a,d);c.lineTo(a+b,d-b/2);c.closePath()}
function draw_pause_symbol(a,d,b,c){c.beginPath();c.moveTo(a+b*0.35,d-b/2);c.lineTo(a+b*0.35,d+b/2);c.lineTo(a,d+b/2);c.lineTo(a,d-b/2);c.lineTo(a+b*0.35,d-b/2);c.moveTo(a+b,d-b/2);c.lineTo(a+b,d+b/2);c.lineTo(a+b-b*0.35,d+b/2);c.lineTo(a+b-b*0.35,d-b/2);c.lineTo(a+b,d-b/2);c.closePath()}
function draw_stop_symbol(a,d,b,c){c.beginPath();c.moveTo(a+b,d-b/2);c.lineTo(a+b,d+b/2);c.lineTo(a,d+b/2);c.lineTo(a,d-b/2);c.lineTo(a+b,d-b/2);c.closePath()}
function draw_cheveron(a,f,d,c,b,e){e.beginPath();e.moveTo(a,f);e.lineTo(a,f+c-b);e.lineTo(a+d/2,f+c);e.lineTo(a+d,f+c-b);e.lineTo(a+d,f);e.lineTo(a+d/2,f+b);e.lineTo(a,f);e.closePath()}
function draw_cheveron_top(a,f,d,c,b,e){e.beginPath();e.moveTo(a+b,f);e.arc(a+b,f+b,b,-Math.PI/2,Math.PI,true);e.lineTo(a,f+c-b);e.lineTo(a+d/2,f+c);e.lineTo(a+d,f+c-b);e.lineTo(a+d,f+b);e.arc(a+d-b,f+b,b,0,-Math.PI/2,true);e.lineTo(a+b,f);e.closePath()}
function draw_cheveron_bottom(a,f,d,c,b,e){e.beginPath();e.moveTo(a,f);e.lineTo(a,f+c-b);e.arc(a+b,f+c-b,b,Math.PI,Math.PI/2,true);e.lineTo(a+d-b,f+c);e.arc(a+d-b,f+c-b,b,Math.PI/2,0,true);e.lineTo(a+d,f+c-b);e.lineTo(a+d,f);e.lineTo(a+d/2,f+b);e.lineTo(a,f);e.closePath()}
function draw_src(a,f,d,c,b,e){e.beginPath();e.moveTo(a+b,f);e.arc(a+b,f+b,b,-Math.PI/2,Math.PI,true);e.lineTo(a,f+c-b);e.arc(a+b,f+c-b,b,Math.PI,Math.PI/2,true);e.lineTo(a+d-b,f+c);e.arc(a+d-b,f+c-b,b,Math.PI/2,0,true);e.lineTo(a+d,f+c-b);e.arc(a+d-b,f+b,b,0,-Math.PI/2,true);e.lineTo(a+b,f);e.closePath()}
function draw_src_down(a,f,d,c,b,e){e.beginPath();e.moveTo(a+b,f);e.arc(a+b,f+b,b,-Math.PI/2,Math.PI,true);e.lineTo(a,f+c/2);e.lineTo(a+d/2,f+c);e.lineTo(a+d,f+c/2);e.arc(a+d-b,f+b,b,0,-Math.PI/2,true);e.lineTo(a+b,f);e.closePath()}
function draw_src_up(a,f,d,c,b,e){e.beginPath();e.moveTo(a,f+c-b);e.arc(a+b,f+c-b,b,Math.PI,Math.PI/2,true);e.lineTo(a+d-b,f+c);e.arc(a+d-b,f+c-b,b,Math.PI/2,0,true);e.lineTo(a+d,f+c/2);e.lineTo(a+d/2,f);e.lineTo(a,f+c/2);e.closePath()}
function in_rect(a,f,d,b,e,c){if((e<a)||(e>(a+d))){return false}else{if((c<f)||(c>(f+b))){return false}else{return true}}}
function above_cheveron(a,h,f,d,c,g,e){var b=true;if(g<(a+f/2)){if(e>(2*c*(g-a)/f+h)){b=false}}else{if(e>(2*c*(a+f-g)/f+h)){b=false}}return b}
function above_uparrow(a,h,f,d,c,g,e){var b=false;if(g<(a+f/2)){if(e<(2*c*(a-g)/f+h+c)){b=true}}else{if(e<(2*c*(g-a-f)/f+h+c)){b=true}}return b}
function in_cheveron(a,g,e,c,b,f,d){if(in_rect(a,g,e,c,f,d)){if(above_cheveron(a,g+c-b,e,c,b,f,d)){if(!above_cheveron(a,g,e,c,b,f,d)){return true}else{return false}}else{return false}}else{return false}}
function in_cheveron_top(a,g,e,c,b,f,d){if(in_rect(a,g,e,c,f,d)){if(above_cheveron(a,g+c-b,e,c,b,f,d)){return true}else{return false}}else{return false}}
function in_cheveron_bottom(a,g,e,c,b,f,d){if(in_rect(a,g,e,c,f,d)){if(!above_cheveron(a,g,e,c,b,f,d)){return true}else{return false}}else{return false}}
function in_src_down(a,g,e,c,b,f,d){if(in_rect(a,g,e,c,f,d)){if(above_cheveron(a,g+c/2,e,c,c/2,f,d)){return true}else{return false}}else{return false}}
function in_src_up(a,g,e,c,b,f,d){if(in_rect(a,g,e,c,f,d)){if(!above_uparrow(a,g,e,c,c/2,f,d)){return true}else{return false}}else{return false}}
function draw_button(k,i,c,b,n,a,l,h,f,e,d,m){var g=false;if(h=="src"){g=in_rect(k,i,c,b,e,d)}else{if(h=="src_d"){g=in_src_down(k,i,c,b,l,e,d)}else{if(h=="src_u"){g=in_src_up(k,i,c,b,l,e,d)}else{if(h=="chev"){g=in_cheveron(k,i,c,b,l,e,d)}else{if(h=="chev_t"){g=in_cheveron_top(k,i,c,b,l,e,d)}else{if(h=="chev_b"){g=in_cheveron_bottom(k,i,c,b,l,e,d)}else{if(h=="circ"){g=false;if(((e-k-c/2)*(e-k-c/2)+(d-i-b/2)*(d-i-b/2))<=(Math.min(c,b)*Math.min(c,b)/4)){g=true}}}}}}}}var j=false;if(f){if(g){if(m){if(a.clicked.line_width&&a.clicked.line_width>0){n.lineWidth=a.clicked.line_width;j=true}n.fillStyle=a.clicked.inner_col;n.strokeStyle=a.clicked.line_col}else{if(a.over.line_width&&a.over.line_width>0){n.lineWidth=a.over.line_width;j=true}n.fillStyle=a.over.inner_col;n.strokeStyle=a.over.line_col}}else{if(a.standard.line_width&&a.standard.line_width>0){n.lineWidth=a.standard.line_width;j=true}n.fillStyle=a.standard.inner_col;n.strokeStyle=a.standard.line_col}}else{if(a.disabled.line_width&&a.disabled.line_width>0){n.lineWidth=a.disabled.line_width;j=true}n.fillStyle=a.disabled.inner_col;n.strokeStyle=a.disabled.line_col}if(h=="src"){draw_src(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="src_d"){draw_src_down(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="src_u"){draw_src_up(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="chev"){draw_cheveron(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="chev_t"){draw_cheveron_top(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="chev_b"){draw_cheveron_bottom(k+n.lineWidth/2,i+n.lineWidth/2,c-n.lineWidth,b-n.lineWidth,l,n)}else{if(h=="circ"){n.beginPath();n.arc(k+c/2,i+b/2,0.5*Math.min(c-n.lineWidth,b-n.lineWidth),0,Math.PI*2,true)}}}}}}}n.fill();if(j){n.stroke()}return(f&&g)}
function drawspeaker(a,f,c,b,e,d){e.strokeStyle=d;e.fillStyle=d;e.lineWidth=c*0.1;e.beginPath();e.moveTo(a,f+c);e.lineTo(a-c*0.6,f+c*0.4);e.lineTo(a-c*0.9,f+c*0.4);e.lineTo(a-c*0.9,f-c*0.4);e.lineTo(a-c*0.6,f-c*0.4);e.lineTo(a,f-c);e.lineTo(a,f+c);e.fill();if(b){e.beginPath();e.arc(a,f,c*0.5,+Math.PI/4,-Math.PI/4,true);e.stroke();e.beginPath();e.arc(a,f,c*0.25,+Math.PI/4,-Math.PI/4,true);e.stroke();e.beginPath();e.arc(a,f,c*0.75,+Math.PI/4,-Math.PI/4,true);e.stroke()}}
function drawclock(a,f,d,c,b,e){e.lineWidth=d*0.1;e.strokeStyle=b;e.fillStyle=b;e.beginPath();e.arc(a,f,d,0,Math.PI*2,false);e.stroke();e.beginPath();e.moveTo(a,f);e.arc(a,f,d,-Math.PI*0.5,Math.PI*(2*c-0.5),false);e.fill()}
function draw_backspace(a,f,d,c,b,e){e.lineWidth=Math.max(Math.min(d,c)*0.1,1);e.strokeStyle=b;e.beginPath();e.moveTo(a+d/2,f);e.lineTo(a-d/2,f);e.moveTo(a-d/4,f-c/4);e.lineTo(a-d/2,f);e.lineTo(a-d/4,f+c/4);e.stroke()}
function draw_text(l,k,f,d,g,i,h,b,e,n,c,m){m.fillStyle=n;m.textAlign="center";m.textBaseline="middle";var j=Math.min(e,d-g*2);if(c){m.font=c+" "+(j).toString()+"px "+fonttype}else{m.font=(j).toString()+"px "+fonttype}var a=m.measureText(i).width;if(a>=(f-g*2)){j=(f-g*2)*j/a}j=Math.max(b,j);if(j>h){if(c){m.font=c+" "+(j).toString()+"px "+fonttype}else{m.font=(j).toString()+"px "+fonttype}m.fillText(i,l+f/2,k+d/2);return true}else{return false}}
function autotext(f,h,j,c,b,e,d,i,k){var g=false;if(d>mintextsize){i.textBaseline="middle";i.textAlign="left";if(h){i.font=h+" "+(Math.floor(d+0.5)).toString()+"px "+fonttype}else{i.font=(Math.floor(d+0.5)).toString()+"px "+fonttype}var a=i.measureText(j).width;if(a>e){if(((d*e/a)>mintextsize)&&((d*e/a)>k)){if(h){i.font=h+" "+(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}else{i.font=(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}if(f){i.lineJoin="round";i.strokeText(j,c-e/2,b)}i.fillText(j,c-e/2,b);g=true}}else{if(f){i.lineJoin="round";i.strokeText(j,c-(a)/2,b)}i.fillText(j,c-(a)/2,b);g=true}}return g}
function autotext2(f,h,l,c,b,e,d,k,p){var g=false;if(d>mintextsize){k.textBaseline="middle";k.textAlign="center";if(h){k.font=h+" "+(Math.floor(d+0.5)).toString()+"px "+fonttype}else{k.font=(Math.floor(d+0.5)).toString()+"px "+fonttype}var n=(l.length)/3;var m=l.split(" ");var j=" ";var i=" ";if(m.length==1){g=autotext(f,h,l,c,b,e,d*1.5,k,p)}else{if(m.length==2){j=(m[0]);i=(m[1])}else{for(var o=(m.length-1);o>=0;o--){if((i.length)>n){j=(" "+m[o]+j)}else{i=(" "+m[o]+i)}}}var a=k.measureText(i).width;if(a<(k.measureText(j).width)){a=k.measureText(j).width}if(a>e){if((d*e/a)>mintextsize){if(p<(d*e/a)){if(h){k.font=h+" "+(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}else{k.font=(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}if(f){k.lineJoin="round";k.strokeText(j,c,b-d*e/a/1.7);k.strokeText(i,c,b+d*e/a/1.7)}k.fillText(j,c,b-d*e/a/1.7);k.fillText(i,c,b+d*e/a/1.7);g=true}}}else{if(p<(d*e/a)){if(f){k.lineJoin="round";k.strokeText(j,c,b-d/1.7);k.strokeText(i,c,b+d/1.7)}k.fillText(j,c,b-d/1.7);k.fillText(i,c,b+d/1.7);g=true}}}}return g}
function autotext3(f,i,m,c,b,e,d,l){var h=false;if(d>mintextsize){l.textBaseline="middle";l.textAlign="center";if(i){l.font=i+" "+(Math.floor(d+0.5)).toString()+"px "+fonttype}else{l.font=(Math.floor(d+0.5)).toString()+"px "+fonttype}var o=(m.length)/4;var n=m.split(" ");var k=" ";var j=" ";var g=" ";if(n.length==1){h=autotext(f,i,m,c,b,e,d*1.5,l,0)}else{if(n.length==2){h=autotext2(f,i,m,c,b,e,d*1.2,l,0)}else{if(n.length==3){k=(n[0]);j=(n[1]);g=(n[2])}else{for(var p=(n.length-1);p>=0;p--){if((g.length)>=o){if((j.length)>=o){k=(" "+n[p]+k)}else{j=(" "+n[p]+j)}}else{g=(" "+n[p]+g)}}}}if((g.length>=(k.length+j.length))||(k.length>=(g.length+j.length))){h=autotext2(f,i,m,c,b,e,d,l,0)}else{var a=l.measureText(j).width;if(a<(l.measureText(k).width)){a=l.measureText(k).width}if(a<(l.measureText(g).width)){a=l.measureText(g).width}if(a>e){if((d*e/a)>mintextsize){if(i){l.font=i+" "+(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}else{l.font=(Math.floor(d*e/a+0.5)).toString()+"px "+fonttype}if(f){l.lineJoin="round";l.strokeText(k,c,b-d*e/a*1.2);l.strokeText(j,c,b);l.strokeText(g,c,b+d*e/a*1.2)}l.fillText(k,c,b-d*e/a*1.2);l.fillText(j,c,b);l.fillText(g,c,b+d*e/a*1.2);h=true}}else{if(f){l.lineJoin="round";l.strokeText(k,c,b-d*1.2);l.strokeText(j,c,b);l.strokeText(g,c,b+d*1.2)}l.fillText(k,c,b-d*1.2);l.fillText(j,c,b);l.fillText(g,c,b+d*1.2);h=true}}}}return h}
function circle_cut_image(e,a,d,b,c,g,f){if(a){e.save();if(f){e.beginPath();e.arc(d,b,c*1.05,0,Math.PI*2,true);e.fillStyle=f;e.fill()}e.save();e.beginPath();e.arc(d,b,c*0.975,0,Math.PI*2,true);e.clip();e.drawImage(a,d-c,b-c,c*2,c*2);e.restore();e.lineWidth=c*0.05;e.strokeStyle=g;e.stroke();e.restore()}}
function rounded_image(h,n,j,i,k,d,m,f,o,l,g){if(n){h.save();if(m){draw_src(j-k/2,i-k/2,k,k,k*0.03,h);h.fillStyle=m;h.fill()}h.save();draw_src(j-k/2,i-k/2,k,k,k*0.03,h);h.clip();if((f)&&(f==true)){var c;var a;var e;if(!o){var b=Math.min(n.width,n.height);c=n.width*k/b;a=0;e=0}else{c=o*k;a=l*k;e=g*k}h.drawImage(n,-n.width*a/c,-n.width*e/c,n.width*k/c,n.width*k/c,j-k/2,i-k/2,k,k)}else{h.drawImage(n,j-k/2,i-k/2,k,k)}h.restore();h.lineWidth=1;h.strokeStyle=d;h.stroke();h.restore()}}
function copyright(e,h,g,a,j,c,b,i,k){e.beginPath();e.arc(h,g,a,0,Math.PI*2,true);e.fillStyle=b;e.lineWidth=a*0.05;e.strokeStyle=i;e.fill();e.stroke();if(typeof(add_MR)==="function"){add_MR(h,g,a)}var f=false;var d=null;if(c&&((((c[0]-h)*(c[0]-h))+((c[1]-g)*(c[1]-g)))<=(a*a))){f=true;d="bold";e.fillStyle=k}else{e.fillStyle=i}if(a>40){if(a>160){autotext3(false,d,j,h,g,a*1.8,a,e,0)}else{autotext3(false,d,j.substr(0,30)+" ...",h,g,a*1.5,a,e,0)}}else{autotext(false,d,"C",h,g,a,a*2,e,0)}return f};

//Leaf_draw.js
function circularOutlinedLeaf(f,a,g,d,c,e,b){f.save();f.beginPath();f.arc(a,g,d-c*0.5,0,Math.PI*2,true);f.fillStyle=e;f.fill();f.strokeStyle=b;f.lineWidth=c;f.stroke();f.restore()}
function naturalLeaf(k,q,o,u,D,n,t,l,p,g,F){k.save();var w=Math.sin(D);var a=Math.cos(D);var E=Math.sin(D+Math.PI/2);var v=Math.cos(D+Math.PI/2);var f=q+Math.cos(D-Math.PI*0.2)*u;var e=o+Math.sin(D-Math.PI*0.2)*u;var C=q+Math.cos(D+Math.PI*0.2)*u;var B=o+Math.sin(D+Math.PI*0.2)*u;var A=Math.sin(D-Math.PI*0.2+Math.PI/2);var G=Math.cos(D-Math.PI*0.2+Math.PI/2);var s=Math.sin(D+Math.PI*0.2+Math.PI/2);var z=Math.cos(D+Math.PI*0.2+Math.PI/2);var j=Math.sin(D+l+p*0.5);var d=Math.cos(D+l+p*0.5);var h=Math.sin(D+l-p*0.5);var b=Math.cos(D+l-p*0.5);var m=q+u*(1+n)*a+u*t*v;var i=o+u*(1+n)*w+u*t*E;k.beginPath();k.arc(q,o,u,D+Math.PI*0.2,D-Math.PI*0.2,false);k.bezierCurveTo(f+u*0.3*G,e+u*0.3*A,m-u*0.15*d,i-u*0.15*j,m,i);k.bezierCurveTo(m-u*0.15*b,i-u*0.15*h,C-u*0.3*z,B-u*0.3*s,C,B);k.fillStyle=F;k.fill();var c=0.88;if(u<20){c=0.8}else{if(u<50){c=0.8+0.08*(u-20)/(20)}}f=q+Math.cos(D-Math.PI*0.2)*u*c;e=o+Math.sin(D-Math.PI*0.2)*u*c;C=q+Math.cos(D+Math.PI*0.2)*u*c;B=o+Math.sin(D+Math.PI*0.2)*u*c;j=Math.sin(D+l+p*0.2);d=Math.cos(D+l+p*0.2);h=Math.sin(D+l-p*0.2);b=Math.cos(D+l-p*0.2);k.beginPath();k.arc(q,o,u*c,D+Math.PI*0.2,D-Math.PI*0.2,false);k.bezierCurveTo(f+u*0.3*G,e+u*0.3*A,m-u*0.15*d,i-u*0.15*j,m,i);k.bezierCurveTo(m-u*0.15*b,i-u*0.15*h,C-u*0.3*z,B-u*0.3*s,C,B);k.fillStyle=g;k.fill();k.restore()}
function randomNaturalLeaf(f,b,h,d,g,e,c){var a=Math.floor(g*112345)%4;if(a==0){naturalLeaf(f,b,h,d,g,0.45,0.25,Math.PI*0.4,Math.PI*0.4,e,c)}if(a==1){naturalLeaf(f,b,h,d,g,0.45,-0.15,0,0.1,e,c)}if(a==2){naturalLeaf(f,b,h,d,g,0.4,-0.25,-Math.PI*0.4,Math.PI*0.2,e,c)}if(a==3){naturalLeaf(f,b,h,d,g,0.45,0.15,0,0.2,e,c)}}
function arcText(c,k,j,a,b,m,f,h,g,l,e){c.save();if(e){c.font=e+" "+((Math.floor(g)).toString()+"px courier")}else{c.font=((Math.floor(g)).toString()+"px courier")}c.fillStyle=l;c.translate(k,j);c.rotate(f);if(m==-1){c.rotate(Math.PI)}for(var d=0;d<b.length;d++){c.save();c.translate(0,m*(-a));c.fillText(b[d],0,0);c.restore();c.rotate(m*h)}c.restore()}
function ghostLeafBase(d,a,g,c,f,e){var b=0;if(c>90){b=3}circularOutlinedLeaf(d,a,g,c*0.935,c*0.015,e.insideColor,e.outlineColor)}
function fullLeafBase(d,h,g,a,b,e,i){var f=0;if(a>20){f=1}if(e==1){circularOutlinedLeaf(d,h,g,a,a*0.12,i.insideColor,i.outlineColor)}else{if(f>0){d.beginPath();var c=a*1.038;d.arc(h,g,c,0,Math.PI*2,true);d.fillStyle=i.BGColor;d.fill()}randomNaturalLeaf(d,h,g,a,b,i.insideColor,i.outlineColor)}}

function ghostLeaf(h,o,m,q,t,l,a,u,d,v,e,b,n){
	var g=0;
	if(q>200){g=4}
	else{if(q>90){g=3}else{if(q>50){g=2}else{if(q>20){g=1}}}}
	var i=null;
	if(g==1){if(l&&(((((l[0]-o)*(l[0]-o))+((l[1]-m)*(l[1]-m)))<=(q*q)))){i="z"}}
	if(g>2) {if(l&&(((((l[0]-o)*(l[0]-o))+((l[1]-m)*(l[1]-m)))<=(q*0.935*q*0.935)))){if(l&&(((((l[0]-o)*(l[0]-o))+((l[1]-m)*(l[1]-m)))>=(q*0.78*q*0.78)))){i="s"}}}
	if(g>2){h.beginPath();h.arc(o,m,q*0.78,0,Math.PI*2,true);h.strokeStyle=n.waterMark;h.lineWidth=q*0.01;h.stroke();var p=("");var c=2.5/Math.max(32,p.length);var k=Math.PI*2/(Math.max(32,p.length))*0.38;var f=(Math.PI-(p.length)*(k))/2;var j=1;if(i=="s"){arcText(h,o,m,q*(0.85),p,j,-Math.PI*(0.5)+j*f,k,q*c,n.textColor,"bold")}else{arcText(h,o,m,q*(0.85),p,j,-Math.PI*(0.5)+j*f,k,q*c,n.sponsorColor,null)}p=("WIKIPEDIA");c=2.5/Math.max(32,p.length);k=Math.PI*2/(Math.max(32,p.length))*0.38;f=(Math.PI-(p.length)*(k))/2;j=-1;if(i=="s"){arcText(h,o,m,q*(0.85),p,j,-Math.PI*(0.5)+j*f,k,q*c,n.textColor,"bold")}else{arcText(h,o,m,q*(0.85),p,j,-Math.PI*(0.5)+j*f,k,q*c,n.sponsorColor,null)}}
	if(g>0) {if(e){if(g<2){if(i=="z"){circle_cut_image(h,e,o,m,q*0.85,n.insideColor,n.highlightColor)}else{circle_cut_image(h,e,o,m,q*0.85,n.insideColor,null)}}else{h.fillStyle=n.textColor;if(g>2){rounded_image(h,e,o,m,q*0.75,n.insideColor,n.highlightColor);var s=m+q*0.34;if(a){if(u){autotext(false,null,"Scientific name: "+u,o,m+q*0.5,q*1,q*0.1,h,3)}autotext2(false,null,a,o,m-q*0.55,q*1,q*0.12,h,3);autotext(false,null,d,o,m+q*0.625,q,q*0.1,h,3)}else{if(u){autotext(false,null,"No common name",o,m+q*0.5,q*1,q*0.1,h,3);autotext2(false,null,u,o,m-q*0.55,q*1,q*0.1,h,3);autotext(false,null,d,o,m+q*0.65,q,q*0.1,h,3)}else{autotext(false,null,"No known name",o,m-q*0.55,q*1,q*0.1,h,3);autotext2(false,null,d,o,m+q*0.55,q*1,q*0.12,h,3)}}if(q*0.035>6){if(copyright(h,o+q*0.43,s,q*0.035,v,l,n.insideColor,n.outlineColor,n.textColor)){i="c"}}}else{if(a){autotext2(false,null,a,o,m-q*0.55,q*1.1,q*0.15,h,3)}else{if(u){autotext2(false,null,u,o,m-q*0.55,q*1.1,q*0.15,h,3)}else{autotext2(false,null,d,o,m-q*0.55,q*1.1,q*0.15,h,3)}}rounded_image(h,e,o,m+q*0.2,q*0.95,n.insideColor,n.highlightColor)}}}else{h.fillStyle=n.textColor;if(g<3){if(a){autotext3(false,null,a,o,m,q*1.25,q*0.3,h,3)}else{if(u){autotext3(false,null,u,o,m,q*1.25,q*0.3,h,3)}else{autotext2(false,null,d,o,m,q*1.25,q*0.3,h,3)}}}else{if(a){if(u){autotext(false,null,"Scientific name: "+u,o,m-q*0.45,q*1,q*0.12,h,3)}autotext2(false,null,a,o,m,q*1.35,q*0.25,h,3);autotext(false,null,d,o,m+q*0.45,q*0.9,q*0.12,h,3)}else{if(u){autotext(false,null,"No common name",o,m-q*0.45,q*1,q*0.12,h,3);autotext2(false,null,u,o,m,q*1.35,q*0.25,h,3);autotext(false,null,d,o,m+q*0.45,q*0.9,q*0.12,h,3)}else{autotext(false,null,"No known name",o,m-q*0.4,q*1,q*0.12,h,3);autotext2(false,null,d,o,m+q*0.2,q*1.35,q*0.25,h,3)}}}}}
	return i
}

function fullLeaf(o,v,t,z,C,g,D,s,F,f,a,E,b,B,G,i,c,u,k,j,h,e){var n=0;if(z>200){n=4}else{if(z>90){n=3}else{if(z>50){n=2}else{if(z>20){n=1}}}}var m=null;if(n==1){if(s&&(((((s[0]-v)*(s[0]-v))+((s[1]-t)*(s[1]-t)))<=(z*z)))){m="z"}}if(n>2){if(s&&(((((s[0]-v)*(s[0]-v))+((s[1]-t)*(s[1]-t)))<=(z*z)))){if(s&&(((((s[0]-v)*(s[0]-v))+((s[1]-t)*(s[1]-t)))>=(z*0.88*z*0.88)))){m="s"}}}if(n>2){var w=(F+f).substr(0,76);if(n<4){if(w.length>44){w=(F).substr(0,44)}else{w=F}}var d=2.5/Math.max(32,w.length);var q=Math.PI*2/(Math.max(32,w.length))*0.38;var l=(Math.PI-(w.length)*(q))/2;var p=1;if((((C)%(Math.PI*2))>(Math.PI))||(g==1)){p=-1}if((m=="s")&&(!D)){arcText(o,v,t,z*(1-0.06),w,p,-Math.PI*(0.5)+p*l,q,z*d,u.highlightColor,"bold")}else{arcText(o,v,t,z*(1-0.06),w,p,-Math.PI*(0.5)+p*l,q,z*d,u.sponsorColor,null)}}if(n>0){if(i){if(n<2){if(m=="z"){circle_cut_image(o,i,v,t,z*0.85,u.outlineColor,u.highlightColor)}else{circle_cut_image(o,i,v,t,z*0.85,u.insideColor,null)}}else{var A=0;o.fillStyle=u.textColor;if(n>2){if(b||B){if(a){autotext(false,"italic",E,v,t+z*0.5,z*1,z*0.1,o,3);autotext2(false,null,a,v,t-z*0.6,z*1.2,z*0.12,o,3)}else{autotext(false,null,"No common name",v,t+z*5,z*1,z*0.1,o,3);autotext2(false,"italic",E,v,t-z*0.6,z*1.2,z*0.12,o,3)}rounded_image(o,i,v,t,z*0.75,u.insideColor,u.highlightColor,k,j,h,e);A=t+z*0.34;autotext(false,null,b,v,t+z*0.625,z,z*0.07,o,3);autotext(false,null,B,v,t+z*0.725,z,z*0.07,o,3)}else{if(a){autotext2(false,"italic",E,v,t+z*0.63,z*1.1,z*0.12,o,3);autotext2(false,null,a,v,t-z*0.55,z*1.2,z*0.15,o,3)}else{autotext2(false,null,"No common name",v,t+z*0.63,z*1.1,z*0.12,o,3);autotext2(false,"italic",E,v,t-z*0.55,z*1.2,z*0.15,o,3)}rounded_image(o,i,v,t+z*0.05,z*0.75,u.insideColor,u.highlightColor,k,j,h,e);A=t+z*0.39}if(z*0.035>6){if(copyright(o,v+z*0.43,A,z*0.035,G,s,u.outlineColor,u.insideColor,u.highlightColor)){m="c"}}}else{if(a){autotext2(false,null,a,v,t-z*0.55,z*1.1,z*0.15,o,3)}else{autotext2(false,"italic",E,v,t-z*0.55,z*1.1,z*0.15,o,3)}rounded_image(o,i,v,t+z*0.2,z*0.95,u.insideColor,u.highlightColor,k,j,h,e)}}}else{o.fillStyle=u.textColor;if(n<3){if(a){autotext3(false,null,a,v,t,z*1.25,z*0.3,o,3)}else{autotext3(false,"italic",E,v,t,z*1.25,z*0.3,o,3)}}else{if(b||B){if(a){autotext2(false,"italic",E,v,t-z*0.5,z*1.1,z*0.15,o,3);autotext2(false,null,a,v,t,z*1.5,z*0.25,o,3)}else{autotext2(false,null,"No common name",v,t-z*0.5,z*1.1,z*0.15,o,3);autotext2(false,"italic",E,v,t,z*1.5,z*0.25,o,3)}autotext(false,null,b,v,t+z*0.45,z,z*0.1,o,3);autotext(false,null,B,v,t+z*0.6,z,z*0.1,o,3)}else{if(a){autotext2(false,"italic",E,v,t-z*0.45,z*1.1,z*0.15,o,3);autotext3(false,null,a,v,t+z*0.2,z*1.4,z*0.2,o,3)}else{autotext2(false,null,"No common name",v,t-z*0.45,z*1.1,z*0.15,o,3);autotext3(false,"italic",E,v,t+z*0.2,z*1.4,z*0.2,o,3)}}}}}return m};